<?php
require_once __DIR__ . "/../auth/auth_check.php";
require_once __DIR__ . "/../config/db.php";
require_once __DIR__ . "/../config/constants.php";

$app_page_title = "รายงาน / Report | IT / AV Task Management System";
$role = strtoupper($_SESSION["role"] ?? "USER");
$user_id = (int) ($_SESSION["user_id"] ?? 0);
$active_nav = "report";
$where = $role === "USER" ? " WHERE t.created_by = ?" : "";
$types = $role === "USER" ? "i" : "";
$params = $role === "USER" ? [$user_id] : [];

$sql = "SELECT t.*, u.username AS created_by_name FROM tasks t INNER JOIN users u ON u.id = t.created_by" . $where . " ORDER BY t.created_at DESC, t.id DESC";
$stmt = $conn->prepare($sql);
if ($types !== "") $stmt->bind_param($types, ...$params);
$stmt->execute();
$tasks = $stmt->get_result();
$task_rows = $tasks->fetch_all(MYSQLI_ASSOC);
$stmt->close();

$counts = ["total" => 0, "pending" => 0, "in_progress" => 0, "completed" => 0, "cancelled" => 0];
foreach ($task_rows as $task) { $key = strtolower(str_replace(" ", "_", $task["status"])); $key = ["รอดำเนินการ"=>"pending","กำลังดำเนินการ"=>"in_progress","เสร็จสิ้น"=>"completed","ยกเลิก"=>"cancelled"][$key] ?? $key; $counts["total"]++; if (isset($counts[$key])) $counts[$key]++; }
$edit_id = isset($_GET["edit"]) ? (int) $_GET["edit"] : 0;
$selected_task = null;
foreach ($task_rows as $task) if ((int) $task["id"] === $edit_id) $selected_task = $task;
function thai_date_time(string $value): string { $time = strtotime($value); return date("d/m/", $time) . (date("Y", $time) + 543) . " " . date("H:i", $time) . " น."; }
function status_meta(string $value): array { $key = strtolower(str_replace(" ", "_", $value)); $key = ["รอดำเนินการ"=>"pending","กำลังดำเนินการ"=>"in_progress","เสร็จสิ้น"=>"completed","ยกเลิก"=>"cancelled"][$key] ?? $key; return [["pending"=>"รอดำเนินการ","in_progress"=>"กำลังดำเนินการ","completed"=>"เสร็จสิ้น","cancelled"=>"ยกเลิก"][$key] ?? $value, ["pending"=>"status-pending","in_progress"=>"status-progress","completed"=>"status-completed","cancelled"=>"status-cancelled"][$key] ?? "status-pending"]; }
require_once __DIR__ . "/../includes/app_header.php";
?>
<div class="app-shell d-flex"><?php require_once __DIR__ . "/../includes/app_sidebar.php"; ?><main class="main-content flex-grow-1 p-4 p-lg-5"><div class="mb-4"><h1 class="page-heading h3 fw-bold mb-1">รายงาน / Report</h1><p class="page-subtitle mb-0">ข้อมูลรายการงานจากฐานข้อมูล</p></div>
<section class="row g-4 mb-4"><div class="col-sm-6 col-xl-3"><article class="card form-card h-100"><div class="card-body"><div class="text-muted small fw-semibold">งานทั้งหมด</div><div class="page-heading h3 fw-bold mb-0"><?php echo $counts["total"]; ?></div></div></article></div><div class="col-sm-6 col-xl-3"><article class="card form-card h-100"><div class="card-body"><div class="text-muted small fw-semibold">กำลังดำเนินการ</div><div class="page-heading h3 fw-bold mb-0"><?php echo $counts["in_progress"]; ?></div></div></article></div><div class="col-sm-6 col-xl-3"><article class="card form-card h-100"><div class="card-body"><div class="text-muted small fw-semibold">เสร็จสิ้น</div><div class="page-heading h3 fw-bold mb-0"><?php echo $counts["completed"]; ?></div></div></article></div><div class="col-sm-6 col-xl-3"><article class="card form-card h-100"><div class="card-body"><div class="text-muted small fw-semibold">ยกเลิก</div><div class="page-heading h3 fw-bold mb-0"><?php echo $counts["cancelled"]; ?></div></div></article></div></section>
<section class="card form-card mb-4"><div class="card-header"><h2 class="section-title mb-0">ค้นหาและกรองรายงาน</h2></div><div class="card-body p-4"><div class="row g-3"><div class="col-md-6 col-xl-4"><label class="form-label">ค้นหาหัวข้องาน</label><input type="search" class="form-control" placeholder="ค้นหาหัวข้องาน"></div><div class="col-md-6 col-xl-2"><label class="form-label">แผนก</label><select class="form-select"><option>ทั้งหมด</option><?php foreach ($departments as $item): ?><option><?php echo $item; ?></option><?php endforeach; ?></select></div><div class="col-md-6 col-xl-2"><label class="form-label">สถานะ</label><select class="form-select"><option>ทั้งหมด</option><?php foreach ($task_status_options as $item): ?><option><?php echo $item; ?></option><?php endforeach; ?></select></div><div class="col-md-6 col-xl-2"><label class="form-label">ประเภทปัญหา</label><select class="form-select"><option>ทั้งหมด</option><?php foreach ($problem_category_options as $item): ?><option><?php echo $item; ?></option><?php endforeach; ?></select></div><div class="col-md-6 col-xl-3"><label class="form-label">วันที่เริ่มต้น</label><input type="text" class="form-control date-picker" placeholder="19/07/2569"></div><div class="col-md-6 col-xl-3"><label class="form-label">วันที่สิ้นสุด</label><input type="text" class="form-control date-picker" placeholder="19/07/2569"></div></div></div></section>
<section class="card form-card"><div class="card-header d-flex justify-content-between"><h2 class="section-title mb-0">รายการรายงาน</h2><span class="text-muted small"><?php echo $counts["total"]; ?> รายการ</span></div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th class="ps-4 py-3">รหัส</th><th>วันที่สร้าง</th><th>หัวข้องาน</th><th>แผนก</th><th>ประเภทปัญหา</th><th>สถานะ</th><th>ผู้สร้าง</th><th class="pe-4 text-end">การจัดการ</th></tr></thead><tbody><?php if (!$task_rows): ?><tr><td colspan="8" class="text-center text-muted py-4">ยังไม่มีข้อมูลงาน</td></tr><?php endif; ?><?php foreach ($task_rows as $task): ?><?php [$label,$class]=status_meta($task["status"]); ?><tr><td class="ps-4 fw-semibold">#T-<?php echo str_pad((string)$task["id"],5,"0",STR_PAD_LEFT); ?></td><td><?php echo thai_date_time($task["created_at"]); ?></td><td><?php echo htmlspecialchars($task["title"],ENT_QUOTES,"UTF-8"); ?></td><td><?php echo htmlspecialchars($task["department"],ENT_QUOTES,"UTF-8"); ?></td><td><?php echo htmlspecialchars($problem_category_options[$task["category"]] ?? $task["category"],ENT_QUOTES,"UTF-8"); ?></td><td><span class="badge rounded-pill <?php echo $class; ?>"><?php echo $label; ?></span></td><td><?php echo htmlspecialchars($task["created_by_name"],ENT_QUOTES,"UTF-8"); ?></td><td class="pe-4 text-end"><button class="btn btn-sm btn-outline-primary" type="button" data-bs-toggle="modal" data-bs-target="#taskModal<?php echo $task["id"]; ?>">ดูรายละเอียด</button> <a class="btn btn-sm btn-outline-secondary" href="?edit=<?php echo $task["id"]; ?>">แก้ไข</a></td></tr><?php endforeach; ?></tbody></table></div></section>
<?php foreach ($task_rows as $task): ?><?php [$label,$class]=status_meta($task["status"]); ?><div class="modal fade" id="taskModal<?php echo $task["id"]; ?>" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h2 class="modal-title fs-5">รายละเอียดงาน #T-<?php echo str_pad((string)$task["id"],5,"0",STR_PAD_LEFT); ?></h2><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-md-6"><strong>หัวข้องาน:</strong> <?php echo htmlspecialchars($task["title"],ENT_QUOTES,"UTF-8"); ?></div><div class="col-md-3"><strong>แผนก:</strong> <?php echo htmlspecialchars($task["department"],ENT_QUOTES,"UTF-8"); ?></div><div class="col-md-3"><strong>สถานะ:</strong> <span class="badge <?php echo $class; ?>"><?php echo $label; ?></span></div><div class="col-md-6"><strong>ประเภทปัญหา:</strong> <?php echo htmlspecialchars($problem_category_options[$task["category"]] ?? $task["category"],ENT_QUOTES,"UTF-8"); ?></div><div class="col-md-6"><strong>สถานที่:</strong> <?php echo htmlspecialchars($task["location"],ENT_QUOTES,"UTF-8"); ?></div><div class="col-12"><strong>รายละเอียดปัญหา:</strong><div class="mt-1"><?php echo nl2br(htmlspecialchars($task["problem"],ENT_QUOTES,"UTF-8")); ?></div></div><div class="col-12"><strong>วิธีแก้ไข:</strong><div class="mt-1"><?php echo nl2br(htmlspecialchars($task["solution"],ENT_QUOTES,"UTF-8")); ?></div></div><div class="col-md-6"><strong>เวลาเริ่ม:</strong> <?php echo thai_date_time($task["start_time"]); ?></div><div class="col-md-6"><strong>เวลาสิ้นสุด:</strong> <?php echo thai_date_time($task["finish_time"]); ?></div><div class="col-12"><strong>หมายเหตุ:</strong> <?php echo nl2br(htmlspecialchars($task["remark"],ENT_QUOTES,"UTF-8")); ?></div><div class="col-md-6"><strong>ผู้สร้าง:</strong> <?php echo htmlspecialchars($task["created_by_name"],ENT_QUOTES,"UTF-8"); ?></div><div class="col-md-6"><strong>สร้างเมื่อ:</strong> <?php echo thai_date_time($task["created_at"]); ?></div><div class="col-md-6"><strong>อัปเดตเมื่อ:</strong> <?php echo thai_date_time($task["updated_at"]); ?></div></div></div><div class="modal-footer"><a class="btn btn-primary" href="?edit=<?php echo $task["id"]; ?>">Edit Task</a><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">ปิด</button></div></div></div></div><?php endforeach; ?>
</main></div>
<?php if ($selected_task): ?><script>window.addEventListener('load',()=>new bootstrap.Modal(document.getElementById('taskModal<?php echo $selected_task["id"]; ?>')).show());</script><?php endif; ?>
<?php require_once __DIR__ . "/../includes/app_footer.php"; ?>
