<?php
// The dashboard is available only after auth_check confirms a valid session.
require_once __DIR__ . "/../auth/auth_check.php";

$username = htmlspecialchars($_SESSION["username"] ?? "Administrator", ENT_QUOTES, "UTF-8");
$department = htmlspecialchars($_SESSION["department"] ?? "IT Department", ENT_QUOTES, "UTF-8");
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard | IT / AV Task Management System</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css" rel="stylesheet">
    <style>
        :root { --navy: #0f172a; --blue: #1769c2; --page-bg: #f4f7fb; --sidebar-width: 260px; }
        body { color: #26394d; background: var(--page-bg); font-family: "Poppins", "Inter", "Segoe UI", sans-serif; }
        .topbar { position: fixed; top: 0; right: 0; left: 0; z-index: 1040; height: 72px; color: #e5edf7; background: #111827; box-shadow: 0 3px 16px rgba(2, 6, 23, .35); }
        .brand-mark { width: 38px; height: 38px; color: #fff; background: linear-gradient(135deg, #237bd1, #103d6d); }
        .brand-title { color: #f8fafc; font-size: 1rem; letter-spacing: -.01em; }
        .sidebar { width: var(--sidebar-width); background: #0f172a; }
        .desktop-sidebar { position: fixed; top: 0; left: 0; z-index: 1030; height: 100vh; padding-top: 5.5rem !important; overflow-y: auto; box-shadow: 4px 0 16px rgba(2, 6, 23, .18); }
        .sidebar .nav-link { color: #cbd5e1; border-radius: .55rem; font-weight: 500; padding: .78rem 1rem; margin-bottom: .25rem; white-space: nowrap; }
        .sidebar .nav-link:hover, .sidebar .nav-link.active { color: #fff; background: #1e293b; }
        .sidebar .nav-link i { width: 1.5rem; font-size: 1.05rem; }
        .sidebar-label { color: #94a3b8; font-size: .68rem; letter-spacing: .1em; white-space: nowrap; }
        .nav-text { display: inline-block; vertical-align: middle; }
        .main-content { min-width: 0; }
        .page-heading { color: var(--navy); }
        .profile-avatar { width: 40px; height: 40px; color: #fff; background: #1e3a5f; }
        .summary-card, .table-card, .chart-card { border: 0; border-radius: .9rem; box-shadow: 0 5px 18px rgba(26, 57, 89, .07); }
        .summary-card { transition: transform .2s ease, box-shadow .2s ease; }
        .summary-card:hover { transform: translateY(-3px); box-shadow: 0 10px 24px rgba(26, 57, 89, .12); }
        .metric-icon { width: 52px; height: 52px; border-radius: .8rem; font-size: 1.4rem; }
        .metric-label { color: #718096; font-size: .82rem; font-weight: 600; letter-spacing: .03em; text-transform: uppercase; }
        .metric-value { color: var(--navy); font-size: 1.7rem; }
        .metric-total { color: #1769c2; background: #e8f2fd; }.metric-pending { color: #b7791f; background: #fff5dd; }.metric-progress { color: #5b4db1; background: #eeeafe; }.metric-completed { color: #21805c; background: #e3f6ed; }
        .table-card .card-header { border-bottom: 1px solid #e8edf3; background: #fff; }.table thead th { color: #718096; background: #f8fafc; border-bottom: 0; font-size: .73rem; letter-spacing: .055em; text-transform: uppercase; }.table td { color: #405367; border-color: #edf1f5; vertical-align: middle; }.task-title { color: #1d3550; font-weight: 600; }
        .badge { font-size: .72rem; font-weight: 600; padding: .48em .7em; }.status-pending { color: #9a640d; background: #fff1cc; }.status-progress { color: #5142a5; background: #e9e4ff; }.status-completed { color: #17734f; background: #dff5e9; }.user-detail { line-height: 1.2; }.profile-username { color: #f8fafc; }.role-badge { display: inline-block; margin-top: .2rem; padding: .18rem .5rem; color: #fff; border-radius: 999px; background: #134e4a; font-size: .69rem; font-weight: 700; letter-spacing: .02em; text-transform: uppercase; }
        .card-subtitle { color: #7d8b9a; font-size: .86rem; }.chart-area { position: relative; height: 300px; }.chart-loader { position: absolute; inset: 0; z-index: 2; display: flex; align-items: center; justify-content: center; border-radius: .9rem; background: rgba(255,255,255,.92); transition: opacity .35s ease, visibility .35s ease; }.chart-loader.is-hidden { visibility: hidden; opacity: 0; }.loader-ring { width: 34px; height: 34px; border: 3px solid #d9e7f6; border-top-color: var(--blue); border-radius: 50%; animation: spin .75s linear infinite; }.legend-dot { width: .7rem; height: .7rem; border-radius: 50%; display: inline-block; }.chart-legend { font-size: .8rem; color: #637489; }
        @keyframes spin { to { transform: rotate(360deg); } }
        .topbar + .d-flex { padding-top: 72px; }
        @media (min-width: 992px) { .desktop-sidebar { display: block !important; } .offcanvas-sidebar { display: none; } .main-content { margin-left: var(--sidebar-width); } }
        @media (max-width: 575.98px) { .topbar { height: 64px; }.topbar + .d-flex { padding-top: 64px; }.brand-title { font-size: .85rem; }.hide-mobile { display: none; }.main-content { padding: 1.5rem !important; }.chart-area { height: 275px; } }
    </style>
</head>
<body>
    <header class="topbar sticky-top d-flex align-items-center px-3 px-lg-4">
        <button class="btn btn-light d-lg-none me-2" type="button" data-bs-toggle="offcanvas" data-bs-target="#sidebarMenu" aria-label="Open navigation"><i class="bi bi-list fs-5"></i></button>
        <a class="d-flex align-items-center text-decoration-none" href="index.php"><span class="brand-mark rounded-3 d-inline-flex align-items-center justify-content-center me-2"><i class="bi bi-grid-1x2-fill"></i></span><span class="brand-title fw-bold">IT / AV Task Management System</span></a>
        <div class="ms-auto d-flex align-items-center gap-3"><div class="d-flex align-items-center gap-2"><span class="profile-avatar rounded-circle d-inline-flex align-items-center justify-content-center"><i class="bi bi-person-fill"></i></span><div class="user-detail hide-mobile"><div class="profile-username fw-semibold small"><?php echo $username; ?></div><span class="role-badge"><?php echo htmlspecialchars($_SESSION["role"] ?? "USER", ENT_QUOTES, "UTF-8"); ?></span></div></div><form method="post" action="../auth/logout.php" class="m-0"><button class="btn btn-outline-danger btn-sm px-3" type="submit"><i class="bi bi-box-arrow-right me-1"></i><span class="hide-mobile">Logout</span></button></form></div>
    </header>
    <div class="d-flex">
        <aside class="sidebar desktop-sidebar d-none p-3"><nav class="nav flex-column"><div class="sidebar-label fw-semibold px-3 mb-2 mt-1">MAIN MENU</div><a class="nav-link active" href="#"><i class="bi bi-speedometer2 me-2"></i><span class="nav-text">Dashboard</span></a><a class="nav-link" href="../task_input/"><i class="bi bi-plus-square me-2"></i><span class="nav-text">บันทึกงาน</span></a><a class="nav-link" href="#"><i class="bi bi-bar-chart-line me-2"></i><span class="nav-text">รายงาน</span></a><div class="sidebar-label fw-semibold px-3 mb-2 mt-4">SYSTEM</div><a class="nav-link" href="#"><i class="bi bi-gear me-2"></i><span class="nav-text">Config</span></a><a class="nav-link" href="#"><i class="bi bi-question-circle me-2"></i><span class="nav-text">คู่มือ</span></a></nav></aside>
        <div class="offcanvas offcanvas-start offcanvas-sidebar sidebar text-white" tabindex="-1" id="sidebarMenu"><div class="offcanvas-header border-bottom border-light border-opacity-25"><h5 class="offcanvas-title">Navigation</h5><button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas"></button></div><div class="offcanvas-body p-3"><nav class="nav flex-column"><a class="nav-link active" href="#"><i class="bi bi-speedometer2 me-2"></i>Dashboard</a><a class="nav-link" href="../task_input/"><i class="bi bi-plus-square me-2"></i>บันทึกงาน</a><a class="nav-link" href="#"><i class="bi bi-bar-chart-line me-2"></i>รายงาน</a><a class="nav-link mt-3" href="#"><i class="bi bi-gear me-2"></i>Config</a><a class="nav-link" href="#"><i class="bi bi-question-circle me-2"></i>คู่มือ</a></nav></div></div>
        <main class="main-content flex-grow-1 p-4 p-lg-5">
            <div class="d-flex align-items-start justify-content-between mb-4"><div><h1 class="page-heading h3 fw-bold mb-1">ภาพรวมแดชบอร์ด</h1><p class="text-muted mb-0">ติดตามกิจกรรมและความคืบหน้าของงานในทีม</p></div><div class="text-end text-muted small d-none d-md-block"><i class="bi bi-calendar3 me-1"></i>18 กรกฎาคม 2026</div></div>
            <section class="row g-4 mb-5" aria-label="สรุปงาน"><div class="col-sm-6 col-xl-3"><article class="card summary-card h-100"><div class="card-body d-flex align-items-center"><div class="metric-icon metric-total d-inline-flex align-items-center justify-content-center me-3"><i class="bi bi-clipboard-data"></i></div><div><div class="metric-label">งานทั้งหมด</div><div class="metric-value fw-bold">128 <span class="fs-6 fw-semibold">งาน</span></div></div></div></article></div><div class="col-sm-6 col-xl-3"><article class="card summary-card h-100"><div class="card-body d-flex align-items-center"><div class="metric-icon metric-pending d-inline-flex align-items-center justify-content-center me-3"><i class="bi bi-hourglass-split"></i></div><div><div class="metric-label">รอดำเนินการ</div><div class="metric-value fw-bold">24 <span class="fs-6 fw-semibold">งาน</span></div></div></div></article></div><div class="col-sm-6 col-xl-3"><article class="card summary-card h-100"><div class="card-body d-flex align-items-center"><div class="metric-icon metric-progress d-inline-flex align-items-center justify-content-center me-3"><i class="bi bi-arrow-repeat"></i></div><div><div class="metric-label">กำลังดำเนินการ</div><div class="metric-value fw-bold">36 <span class="fs-6 fw-semibold">งาน</span></div></div></div></article></div><div class="col-sm-6 col-xl-3"><article class="card summary-card h-100"><div class="card-body d-flex align-items-center"><div class="metric-icon metric-completed d-inline-flex align-items-center justify-content-center me-3"><i class="bi bi-check2-circle"></i></div><div><div class="metric-label">เสร็จสิ้น</div><div class="metric-value fw-bold">68 <span class="fs-6 fw-semibold">งาน</span></div></div></div></article></div></section>

            <!-- Monitor section: fake data is declared below and can later be replaced with database values. -->
            <section class="mb-5" aria-labelledby="monitor-heading"><div class="mb-4"><h2 id="monitor-heading" class="page-heading h4 fw-bold mb-1">ติดตามกิจกรรมและความคืบหน้างาน</h2><p class="text-muted mb-0">สรุปการกระจายงานและกิจกรรมในสัปดาห์ปัจจุบัน</p></div><div class="row g-4"><div class="col-lg-5"><article class="card chart-card h-100"><div class="card-body p-4"><h3 class="page-heading h5 fw-bold mb-1">ความคืบหน้างาน</h3><p class="card-subtitle mb-3">สถานะการดำเนินงานในปัจจุบัน</p><div class="chart-area"><div class="chart-loader" id="progressLoader"><span class="loader-ring"></span></div><canvas id="progressChart"></canvas></div><div class="chart-legend d-flex flex-wrap justify-content-center gap-3 mt-2"><span><i class="legend-dot me-1" style="background:#21805c"></i>เสร็จสิ้น</span><span><i class="legend-dot me-1" style="background:#e8ae37"></i>รอดำเนินการ</span><span><i class="legend-dot me-1" style="background:#6c5dc7"></i>กำลังดำเนินการ</span></div></div></article></div><div class="col-lg-7"><article class="card chart-card h-100"><div class="card-body p-4"><h3 class="page-heading h5 fw-bold mb-1">แนวโน้มกิจกรรมงาน</h3><p class="card-subtitle mb-3">จำนวนงานที่บันทึกในแต่ละวันของสัปดาห์นี้</p><div class="chart-area"><div class="chart-loader" id="activityLoader"><span class="loader-ring"></span></div><canvas id="activityChart"></canvas></div></div></article></div></div></section>

            <section class="card table-card"><div class="card-header d-flex align-items-center justify-content-between py-3 px-4"><div><h2 class="h5 mb-1 fw-bold page-heading">งานล่าสุด</h2><p class="text-muted small mb-0">อัปเดตงานล่าสุดจากทุกแผนก</p></div><button class="btn btn-primary btn-sm px-3" type="button"><i class="bi bi-list-check me-1"></i>ดูทั้งหมด</button></div><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th class="ps-4 py-3">หัวข้องาน</th><th class="py-3">แผนก</th><th class="py-3">สถานะ</th><th class="pe-4 py-3">วันที่</th></tr></thead><tbody><tr><td class="ps-4 task-title">บำรุงรักษาโปรเจคเตอร์ - ห้องประชุม A</td><td>ฝ่ายสนับสนุน IT</td><td><span class="badge status-progress rounded-pill">กำลังดำเนินการ</span></td><td class="pe-4">18 ก.ค. 2026</td></tr><tr><td class="ps-4 task-title">ติดตั้งระบบเสียงสำหรับการประชุมไตรมาส</td><td>ทีม AV</td><td><span class="badge status-pending rounded-pill">รอดำเนินการ</span></td><td class="pe-4">17 ก.ค. 2026</td></tr><tr><td class="ps-4 task-title">คำขอสิทธิ์เข้าใช้เครือข่ายสำหรับพนักงานใหม่</td><td>ฝ่ายทรัพยากรบุคคล</td><td><span class="badge status-completed rounded-pill">เสร็จสิ้น</span></td><td class="pe-4">17 ก.ค. 2026</td></tr><tr><td class="ps-4 task-title">เปลี่ยนสาย HDMI ในห้องฝึกอบรม</td><td>ฝ่ายปฏิบัติการ</td><td><span class="badge status-completed rounded-pill">เสร็จสิ้น</span></td><td class="pe-4">16 ก.ค. 2026</td></tr><tr><td class="ps-4 task-title">กำหนดค่าจอประชาสัมพันธ์ดิจิทัล</td><td>ฝ่ายการตลาด</td><td><span class="badge status-progress rounded-pill">กำลังดำเนินการ</span></td><td class="pe-4">16 ก.ค. 2026</td></tr></tbody></table></div></section>
        </main>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.8/dist/chart.umd.min.js"></script>
    <script>
        // Fake data arrays only. Replace these values when a data source is available.
        const taskProgressData = [68, 24, 36];
        const taskProgressLabels = ['เสร็จสิ้น', 'รอดำเนินการ', 'กำลังดำเนินการ'];
        const activityLabels = ['จันทร์', 'อังคาร', 'พุธ', 'พฤหัสบดี', 'ศุกร์', 'เสาร์', 'อาทิตย์'];
        const activityValues = [12, 18, 25, 19, 30, 15, 10];
        const corporateTooltip = { backgroundColor: '#102b49', titleFont: { weight: '600' }, bodyFont: { weight: '500' }, padding: 12, cornerRadius: 7 };
        const progressCenterText = { id: 'progressCenterText', afterDraw(chart) { const { ctx, chartArea: { left, right, top, bottom } } = chart; const total = taskProgressData.reduce((sum, value) => sum + value, 0); const percent = Math.round((taskProgressData[0] / total) * 100); const x = (left + right) / 2; const y = top + (bottom - top) * .72; ctx.save(); ctx.textAlign = 'center'; ctx.fillStyle = '#102b49'; ctx.font = '700 26px Segoe UI'; ctx.fillText(percent + '%', x, y); ctx.fillStyle = '#718096'; ctx.font = '500 12px Segoe UI'; ctx.fillText('เสร็จสิ้น', x, y + 20); ctx.restore(); } };
        new Chart(document.getElementById('progressChart'), { type: 'doughnut', plugins: [progressCenterText], data: { labels: taskProgressLabels, datasets: [{ data: taskProgressData, backgroundColor: ['#21805c', '#e8ae37', '#6c5dc7'], borderColor: '#fff', borderWidth: 4, borderRadius: 5, hoverOffset: 8 }] }, options: { responsive: true, maintainAspectRatio: false, cutout: '68%', rotation: -90, circumference: 180, animation: { animateRotate: true, animateScale: true, duration: 1200, easing: 'easeOutQuart' }, plugins: { legend: { display: false }, tooltip: { ...corporateTooltip, callbacks: { label: c => { const total = c.dataset.data.reduce((sum, value) => sum + value, 0); return ` ${c.label}: ${c.raw} งาน (${Math.round(c.raw / total * 100)}%)`; } } } } } });
        new Chart(document.getElementById('activityChart'), { type: 'line', data: { labels: activityLabels, datasets: [{ label: 'งาน', data: activityValues, borderColor: '#1769c2', backgroundColor: 'rgba(23,105,194,.10)', fill: true, tension: .38, borderWidth: 3, pointRadius: 4, pointHoverRadius: 6, pointBackgroundColor: '#fff', pointBorderColor: '#1769c2', pointBorderWidth: 3 }] }, options: { responsive: true, maintainAspectRatio: false, animation: { duration: 1100, easing: 'easeOutQuart' }, interaction: { intersect: false, mode: 'index' }, scales: { x: { grid: { display: false }, border: { display: false }, ticks: { color: '#718096' } }, y: { beginAtZero: true, suggestedMax: 35, border: { display: false }, grid: { color: '#e8edf3' }, ticks: { color: '#718096', precision: 0, stepSize: 5 } } }, plugins: { legend: { display: false }, tooltip: { ...corporateTooltip, callbacks: { label: c => ` งาน: ${c.parsed.y}` } } } } });
        window.addEventListener('load', () => { setTimeout(() => document.getElementById('progressLoader').classList.add('is-hidden'), 350); setTimeout(() => document.getElementById('activityLoader').classList.add('is-hidden'), 500); });
    </script>
</body>
</html>
